### ISSUE TITLE
Error while including twig-loader in Laravel Webpack (mix)

### ISSUE THREAD

**Issue by WickedSik** [zimmo-be/twig-loader#28]
The error message

```
error  in ./resources/assets/js/admin/htk/message.twig

Module parse failed: /Users/jurriendokter/Development/holland-toolkit/resources/assets/js/admin/htk/message.twig Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <div class="row large-12 columns">
|     <div class="callout {{ type }}" data-closable>
|         <h6>{{ title }}</h6>

 @ ./resources/assets/js/admin/htk/messages.js 2:17-42
 @ ./resources/assets/js/admin/holland-toolkit.js
 @ ./resources/assets/js/admin/bootstrap.js
 @ ./resources/assets/js/admin.js
 @ multi ./resources/assets/js/admin.js
```

My config:

```
mix.webpackConfig({
        module: {
            loaders: [
                { test: /\.twig$/, loader: 'twig-loader' }
            ]
        },
        node: {
            fs: "empty"
        }
    })
   // ... some js / sass calls
   .version()
;
```

The line in question: `const messageTpl = require('./message.twig');`

I have googled, but yet to find an answer, could you perhaps aid me?

I did try `const messageTpl = require('twig!./message.twig');` but that crashes my build with the following message.

```
                       throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
                        ^

Error: Module '/Users/jurriendokter/Development/holland-toolkit/node_modules/twig/twig.min.js' is not a loader (must have normal or pitch function)
    at loadLoader (/Users/jurriendokter/Development/holland-toolkit/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/jurriendokter/Development/holland-toolkit/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/jurriendokter/Development/holland-toolkit/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/jurriendokter/Development/holland-toolkit/node_modules/webpack/lib/NormalModule.js:179:3)
    at NormalModule.build (/Users/jurriendokter/Development/holland-toolkit/node_modules/webpack/lib/NormalModule.js:268:15)
    at Compilation.buildModule (/Users/jurriendokter/Development/holland-toolkit/node_modules/webpack/lib/Compilation.js:142:10)
    at factoryCallback (/Users/jurriendokter/Development/holland-toolkit/node_modules/webpack/lib/Compilation.js:325:11)
    at factory (/Users/jurriendokter/Development/holland-toolkit/node_modules/webpack/lib/NormalModuleFactory.js:253:5)
    at applyPluginsAsyncWaterfall (/Users/jurriendokter/Development/holland-toolkit/node_modules/webpack/lib/NormalModuleFactory.js:99:14)
    at /Users/jurriendokter/Development/holland-toolkit/node_modules/tapable/lib/Tapable.js:204:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/Users/jurriendokter/Development/holland-toolkit/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/jurriendokter/Development/holland-toolkit/node_modules/tapable/lib/Tapable.js:208:13)
    at resolver (/Users/jurriendokter/Development/holland-toolkit/node_modules/webpack/lib/NormalModuleFactory.js:74:11)
    at process.nextTick (/Users/jurriendokter/Development/holland-toolkit/node_modules/webpack/lib/NormalModuleFactory.js:205:8)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by webberig** [comment]
Which version of webpack are you using ?
